name: hydrate_app
description: Water tracker app
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  intl: ^0.19.0
  shared_preferences: ^2.2.0
  flutter_animate: ^4.2.0

flutter:
  uses-material-design: true
